-- Run this migration in Supabase SQL Editor before using live hostel records.
-- The browser app only uses the publishable key; RLS keeps each student's rows private.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role text not null default 'student' check (role in ('student', 'admin', 'warden')),
  roll_no text,
  course text,
  room_no text,
  block text,
  floor text,
  phone text,
  parent_name text,
  parent_phone text,
  parent_relation text,
  parent_email text,
  home_address text,
  blood_group text,
  date_of_joining date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.students (
  id text primary key,
  user_id uuid unique references auth.users(id) on delete set null,
  parent_id text,
  name text not null,
  roll_no text not null,
  course text not null,
  room_no text,
  year text,
  status text not null default 'Active' check (status in ('Active', 'Inactive')),
  phone text,
  parent_name text,
  parent_phone text,
  parent_relation text,
  parent_email text,
  home_address text,
  blood_group text,
  email text,
  date_of_joining date,
  created_at timestamptz not null default now()
);

create table if not exists public.rooms (
  room_no text primary key,
  block text not null,
  floor text not null,
  capacity integer not null default 0,
  occupied integer not null default 0,
  status text not null default 'Available' check (status in ('Available', 'Full', 'Maintenance'))
);

create table if not exists public.fees (
  id text primary key,
  user_id uuid references auth.users(id) on delete cascade,
  student_name text not null,
  roll_no text,
  semester text,
  amount numeric not null default 0,
  paid numeric not null default 0,
  due_date date,
  method text,
  created_at timestamptz not null default now()
);

create table if not exists public.complaints (
  id text primary key,
  user_id uuid references auth.users(id) on delete cascade,
  student_name text not null,
  room_no text,
  category text not null,
  description text not null,
  status text not null default 'Pending' check (status in ('Pending', 'In Progress', 'Resolved')),
  created_at timestamptz not null default now()
);

create table if not exists public.notices (
  id text primary key,
  title text not null,
  body text not null,
  audience text not null default 'All residents',
  posted_at date not null default current_date,
  pinned boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  student_name text not null,
  room_no text,
  date date not null,
  status text not null check (status in ('Present', 'Absent', 'Leave')),
  marked_by text,
  created_at timestamptz not null default now(),
  unique (user_id, date)
);

create table if not exists public.leave_requests (
  id text primary key,
  user_id uuid references auth.users(id) on delete cascade,
  student_name text not null,
  from_date date not null,
  to_date date not null,
  reason text not null,
  status text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.outpasses (
  id text primary key,
  user_id uuid references auth.users(id) on delete cascade,
  student_name text not null,
  roll_no text,
  reason text not null,
  departure timestamptz not null,
  expected_return timestamptz not null,
  status text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.mess_menu (
  id bigint generated by default as identity primary key,
  day text not null,
  breakfast text not null,
  lunch text not null,
  snacks text not null,
  dinner text not null,
  unique (day)
);

create table if not exists public.settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.students enable row level security;
alter table public.rooms enable row level security;
alter table public.fees enable row level security;
alter table public.complaints enable row level security;
alter table public.notices enable row level security;
alter table public.attendance enable row level security;
alter table public.leave_requests enable row level security;
alter table public.outpasses enable row level security;
alter table public.mess_menu enable row level security;
alter table public.settings enable row level security;

create or replace function public.is_hms_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('admin', 'warden')
  );
$$;

drop policy if exists "users read own profile" on public.profiles;
drop policy if exists "users insert own profile" on public.profiles;
drop policy if exists "users update own profile" on public.profiles;
drop policy if exists "users read own student record" on public.students;
drop policy if exists "users insert own student record" on public.students;
drop policy if exists "users update own student record" on public.students;
drop policy if exists "staff read students" on public.students;
drop policy if exists "users read own fees" on public.fees;
drop policy if exists "staff read fees" on public.fees;
drop policy if exists "users read own complaints" on public.complaints;
drop policy if exists "staff read complaints" on public.complaints;
drop policy if exists "users create own complaints" on public.complaints;
drop policy if exists "users read notices" on public.notices;
drop policy if exists "users read own attendance" on public.attendance;
drop policy if exists "staff read attendance" on public.attendance;
drop policy if exists "users read own leaves" on public.leave_requests;
drop policy if exists "staff read leaves" on public.leave_requests;
drop policy if exists "users create own leaves" on public.leave_requests;
drop policy if exists "users read own outpasses" on public.outpasses;
drop policy if exists "staff read outpasses" on public.outpasses;
drop policy if exists "users create own outpasses" on public.outpasses;
drop policy if exists "users read rooms" on public.rooms;
drop policy if exists "users read menu" on public.mess_menu;
drop policy if exists "users read settings" on public.settings;

create policy "users read own profile" on public.profiles
  for select using (id = auth.uid() or public.is_hms_staff());
create policy "users insert own profile" on public.profiles
  for insert with check (id = auth.uid());
create policy "users update own profile" on public.profiles
  for update using (id = auth.uid()) with check (id = auth.uid());

create policy "users read own student record" on public.students
  for select using (user_id = auth.uid());
create policy "users insert own student record" on public.students
  for insert with check (user_id = auth.uid());
create policy "users update own student record" on public.students
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "staff read students" on public.students
  for select using (public.is_hms_staff());

create policy "users read own fees" on public.fees
  for select using (user_id = auth.uid());
create policy "staff read fees" on public.fees
  for select using (public.is_hms_staff());

create policy "users read own complaints" on public.complaints
  for select using (user_id = auth.uid());
create policy "staff read complaints" on public.complaints
  for select using (public.is_hms_staff());
create policy "users create own complaints" on public.complaints
  for insert with check (user_id = auth.uid());

create policy "users read notices" on public.notices
  for select using (auth.uid() is not null);

create policy "users read own attendance" on public.attendance
  for select using (user_id = auth.uid());
create policy "staff read attendance" on public.attendance
  for select using (public.is_hms_staff());

create policy "users read own leaves" on public.leave_requests
  for select using (user_id = auth.uid());
create policy "staff read leaves" on public.leave_requests
  for select using (public.is_hms_staff());
create policy "users create own leaves" on public.leave_requests
  for insert with check (user_id = auth.uid());

create policy "users read own outpasses" on public.outpasses
  for select using (user_id = auth.uid());
create policy "staff read outpasses" on public.outpasses
  for select using (public.is_hms_staff());
create policy "users create own outpasses" on public.outpasses
  for insert with check (user_id = auth.uid());

create policy "users read rooms" on public.rooms
  for select using (auth.uid() is not null);
create policy "users read menu" on public.mess_menu
  for select using (auth.uid() is not null);
create policy "users read settings" on public.settings
  for select using (auth.uid() is not null);

create or replace function public.handle_new_hms_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  user_role text := 'student';
begin
  if new.raw_user_meta_data->>'role' in ('admin', 'warden', 'student') then
    user_role := new.raw_user_meta_data->>'role';
  end if;

  insert into public.profiles (id, full_name, role, roll_no, course, room_no, block, floor, phone)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data->>'full_name', ''), split_part(new.email, '@', 1)),
    user_role,
    nullif(new.raw_user_meta_data->>'roll_no', ''),
    nullif(new.raw_user_meta_data->>'course', ''),
    nullif(new.raw_user_meta_data->>'room_no', ''),
    nullif(new.raw_user_meta_data->>'block', ''),
    nullif(new.raw_user_meta_data->>'floor', ''),
    nullif(new.raw_user_meta_data->>'phone', '')
  )
  on conflict (id) do update set
    full_name = excluded.full_name,
    role = excluded.role,
    roll_no = excluded.roll_no,
    course = excluded.course,
    room_no = excluded.room_no,
    block = excluded.block,
    floor = excluded.floor,
    phone = excluded.phone,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_hms_user();

-- Backfill profiles for users created before the trigger was installed.
insert into public.profiles (id, full_name, role)
select
  u.id,
  coalesce(nullif(u.raw_user_meta_data->>'full_name', ''), split_part(u.email, '@', 1)),
  case
    when u.raw_user_meta_data->>'role' in ('admin', 'warden', 'student')
      then u.raw_user_meta_data->>'role'
    else 'student'
  end
from auth.users u
where not exists (
  select 1 from public.profiles p where p.id = u.id
);

-- Repair profiles created with a valid role in their Auth metadata.
update public.profiles p
set role = u.raw_user_meta_data->>'role',
    updated_at = now()
from auth.users u
where p.id = u.id
  and u.raw_user_meta_data->>'role' in ('admin', 'warden', 'student');
